### ISSUE TITLE
Move cfg function to a separate HPP file ...

### ISSUE THREAD

**Issue by MisterHLunaticwraith** [RedBelette/RED_FRAMEWORK#41]
and #include in the cpp
that's what i do in my mods for clarity's sake

**Comment by RedBelette** [comment]
I think that's not a good idea for this addon. In the config file we declare only the functions. I don't close this issue, if you have others arguments don't hesitate to inform me.

**Comment by MisterHLunaticwraith** [comment]
If you want to include modules you will have to declare more than just the functions,  cfg modules are used with modules, (been there, done that, it will get messy)

**Comment by MisterHLunaticwraith** [comment]
https://github.com/MisterHLunaticwraith/MRHSatellite/tree/master/cfgHPP how I did it

**Comment by RedBelette** [comment]
The core project need to be as transparent as possible. No sounds, no marker, no retexturing, no external or internal modules ... Only functions are needed. 

The other future project called "RedFramework Gui" will use the core project and will add somes more features like sounds, interface, retexturing (why not). I think it's a good candidate to your idea. 

Do you understand the goal of the core project? 
To explain it, the core project need to be light and not invasive, so that a mission maker can use it in its own way. Without polution. 

If the user want more stuff, so he need to use the project gui.

**Comment by MisterHLunaticwraith** [comment]
ok!

**Comment by MisterHLunaticwraith** [comment]
point well made!
